### ISSUE TITLE
Проблема в Шиндовс

### ISSUE THREAD

**Issue by MrROBUST** [for2ch/Linux-F.A.Q#7]
Пытаюсь клонировать реп через git + TortoiseGit, получаю ошибку:

```
git.exe clone --progress -v "https://github.com/MrROBUST/Linux-F.A.Q" "D:\texts\Linux-F.A.Q"

Cloning into 'D:\texts\Linux-F.A.Q'...
POST git-upload-pack (250 bytes)
remote: Counting objects: 526, done.
Receiving objects: 100% (526/526), 1.07 MiB | 759.00 KiB/s, done.
Resolving deltas: 100% (263/263), done.
remote: Total 526 (delta 0), reused 0 (delta 0), pack-reused 526
Checking connectivity... done.
error: unable to create file Шапка для "нубских вопросов": Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'



git did not exit cleanly (exit code 128) (2996 ms @ 30.07.2016 18:12:46)
```

Может проблема в имени файла?

**Comment by for2ch** [comment]
Сейчас посмотрю.
Ты клонируешь вики?

**Comment by MrROBUST** [comment]
Нет, https://github.com/for2ch/Linux-F.A.Q/

**Comment by for2ch** [comment]
Да, гитхабовское приложение на винде тоже не работает.

> 2016-08-01 05:50:25.9867|ERROR|thread:17|ComparisonGraph|JavaScript Alert from the comparison graph: http://github-app/: TypeError: Cannot read property 'selectCommit' of null

Есть идеи по дебагу?

**Comment by MrROBUST** [comment]
Виндовс не дает создать файл с символом двойной кавычки в названии
http://stackoverflow.com/questions/26097568/git-pull-error-unable-to-create-file-invalid-argument

**Comment by for2ch** [comment]
Спасибо. Сейчас буду проверять все названия файлов.

**Comment by MrROBUST** [comment]
Теперь скачивается.
